- name: git checkout code latest
  git:
    repo: 'https://github.com/atisak/demo-nodejs-mongodb-rest.git'
    dest: /tmp/demo-nodejs-mongodb-rest
    version: master

- name: Build docker images
  command: docker build -f /tmp/demo-nodejs-mongodb-rest/Dockerfile -t atisak/demo-nodejs:"{{ tagnumber }}" /tmp/demo-nodejs-mongodb-rest

- name: Docker tag images
  command: docker tag atisak/demo-nodejs:"{{ tagnumber }}" atisak/demo-nodejs:latest

- name: Docker push
  command: docker push atisak/demo-nodejs:latest 

  - name: Ansible delete file glob
    find:
      paths: /tmp/demo-nodejs-mongodb-rest
      patterns: *
    register: files_to_delete

  - name: Ansible remove file glob
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"