- name: git checkout code latest
  git:
    repo: 'https://github.com/atisak/demo-nodejs-mongodb-rest.git'
    dest: /tmp/
    version: master

- name: Build docker images
  command: docker build -f /tmp/demo-nodejs-mongodb-rest/Dockerfile -t atisak/demo-nodejs /tmp/demo-nodejs-mongodb-rest

- name: Docker tag images
  command: docker tag atisak/demo-nodejs:{{ tagnumber }} atisak/demo-nodejs:latest

- name: Docker push
  command: docker push atisak/demo-nodejs:latest 