version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: always
#   environment:
#      JENKINS_JAVA_OPTIONS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
    ports:
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $(which docker):$(which docker)
    - $(which docker-compose):$(which docker-compose)
    - jenkins-volume:/var/jenkins_home
    - /etc/timezone:/etc/timezone 

    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '5'
volumes:
  jenkins-volume: {}
